version: '2'

services:

  antic-comparteix-net:
    image: nginx:alpine
    container_name: antic-comparteix-net
    restart: always
    ports:
      - "80"
    networks:
      - server_frontend
    volumes:
      - ./src:/var/www/html
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: antic.comparteix.net
      LETSENCRYPT_HOST: antic.comparteix.net,comparteix.net
      LETSENCRYPT_EMAIL: admin@comparteix.net

networks:
  server_frontend:
    external: true
