server {

    server_name _;
    root /var/www/html;

    index index.html index.htm index.php;

    error_page 404  /mirror/error404.html;

    # cache configuration for most common files
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        # Some basic cache-control for static files to be sent to the browser
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    # drop common log errors
    location = /robots.txt { access_log off; log_not_found off; }
    location = /favicon.ico { access_log off; log_not_found off; }

    location = / {
        return 301 $scheme://antic.comparteix.net/mirror$request_uri;
    }

    location /mirror {
        location ~ download\.php\@sid=[0-9]+$ {
            types {}
            default_type image/jpeg;
        }

        location ~ ^/mirror/descarrega(?:_rapida)?\.php$ {

            if ($args ~ "sid=[0-9]+&url=ed2k(?:%3A|:)(?:/|%2F){2}(?:\||%7C)file(?:\||%7C)(?:(?:[^|%]|%[^7])*)(?:\||%7C)(?:(?:[^|%]|%[^7])*)(?:\||%7C)((?:[^|%]|%[^7])*)") {
                return 301 http://ed2k.shortypower.org/?hash=$1;
            }
        }

        location ~ ^(/mirror/.+\.php)$ {
            if ($args) {
                return 301 $1@$args.html;
            }
            return 301 $1.html;
        }

        location ~ ^/mirror/(add|vote|comment|edit|del|del_comment)\.php\@ {
            return 301 /mirror/$1.php.html;
        }

        location ~ rss.*\.php {
            return 301 /mirror/rss.xml;
        }
    }
}
